Repository ArthuryanLoheac/RayTracer, pull requests merged in 2025-05, with the labels that each got.

#31 :sparkles: multiple objects element
  include/Generation/tools.hpp
  main.cpp
  src/3dDatas/Point3D.cpp
  src/3dDatas/Point3D.hpp
  src/Draw/computeTreeValues.cpp
  src/Draw/draw.cpp
  src/Draw/show.cpp
  src/Interfaces/Light/A_Light.cpp
  src/Interfaces/Light/A_Light.hpp
  src/Interfaces/Primitive/A_Primitive.cpp
  src/Interfaces/Primitive/A_Primitive.hpp
  src/Interfaces/Primitive/I_Primitive.hpp
  src/Lights/Spot.cpp
  src/Primitive/PrimSphere.cpp
  src/Scene/Scene.cpp
  src/Scene/Scene.hpp
  tests/t1.txt
Labels: enhancement

#29 :sparkles: ouput-a-ppm-file
  .gitignore
  Makefile
  include/Generation/tools.hpp
  src/Draw/createImage.cpp
  src/Draw/draw.cpp
  src/Draw/show.cpp
Labels: enhancement

#32 :sparkles: gestion des angles des spots
  src/3dDatas/Point3D.hpp
  src/3dDatas/Vector3D.cpp
  src/3dDatas/Vector3D.hpp
  src/Draw/draw.cpp
  src/Lights/Spot.cpp
  src/Primitive/PrimSphere.cpp
  src/Scene/Camera.cpp
Labels: enhancement

#34 🩹 Fix random generator to generate different string each runtime
  src/Draw/createImage.cpp
Labels: bug

#39 :sparkles: Better lighting & cast shadow & multiple lights handling
  include/Generation/tools.hpp
  main.cpp
  renders/screenshot/.gitkeep
  src/3dDatas/Point3D.cpp
  src/3dDatas/Point3D.hpp
  src/3dDatas/Vector3D.cpp
  src/3dDatas/Vector3D.hpp
  src/Draw/computeTreeValues.cpp
  src/Draw/draw.cpp
  src/Interfaces/Light/A_Light.cpp
  src/Interfaces/Light/A_Light.hpp
  src/Interfaces/Light/I_Light.hpp
  src/Interfaces/Primitive/I_Primitive.hpp
  src/Lights/Ambient.cpp
  src/Lights/Ambient.hpp
  src/Lights/Spot.cpp
  src/Lights/Spot.hpp
  src/Primitive/PrimSphere.cpp
  src/Primitive/PrimSphere.hpp
  src/Scene/Scene.hpp
Labels: enhancement

#58 :sparkles: planeso
  Makefile
  main.cpp
  src/Draw/draw.cpp
  src/Interfaces/Light/A_Light.cpp
  src/Interfaces/Light/A_Light.hpp
  src/Interfaces/Light/I_Light.hpp
  src/Lights/Ambient.cpp
  src/Lights/Ambient.hpp
  src/Lights/Spot.cpp
  src/Lights/Spot.hpp
  src/Material/FlatMat.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimPlane.hpp
  src/Primitive/PrimSphere.cpp
  src/Scene/Scene.hpp
Labels: enhancement

#59 :sparkles: colored light
  main.cpp
  src/Draw/draw.cpp
  src/Interfaces/Light/A_Light.cpp
  src/Interfaces/Light/A_Light.hpp
  src/Interfaces/Light/I_Light.hpp
  src/Lights/Ambient.cpp
  src/Lights/Spot.cpp
  src/Primitive/PrimSphere.cpp
Labels: enhancement

#62 ✨ Add antialiasing
  Makefile
  include/Generation/tools.hpp
  main.cpp
  src/Draw/antiAliasing.cpp
  src/Draw/draw.cpp
  src/Draw/my_Image.cpp
  src/Draw/my_Image.hpp
  src/Draw/show.cpp
  src/Lights/Spot.cpp
  src/Primitive/PrimSphere.cpp
  tests/test_antiAliasing.cpp
Labels: enhancement

#63 :sparkles: primitive cone
  Makefile
  main.cpp
  src/3dDatas/Vector3D.cpp
  src/3dDatas/Vector3D.hpp
  src/Interfaces/Primitive/A_Primitive.cpp
  src/Interfaces/Primitive/A_Primitive.hpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimCone.hpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimSphere.cpp
Labels: enhancement

#61 :sparkles: constructeurs factory
  src/DesignPatterns/Factory.cpp
  src/DesignPatterns/Factory.hpp
Labels: enhancement

#65 ✨ Add handling of the modification of the file during the runtime
  include/Generation/tools.hpp
  main.cpp
  src/Draw/draw.cpp
  src/Draw/show.cpp
  src/Parsing/Parsing.cpp
  tests/t2.cfg
Labels: enhancement

#67 :sparkles: material texturing from image
  Makefile
  assets/earth.jpg
  assets/images.jpeg
  assets/shrek-5.jpg
  main.cpp
  src/DesignPatterns/Factory.cpp
  src/DesignPatterns/Factory.hpp
  src/Material/ImageMat.cpp
  src/Material/ImageMat.hpp
  src/Material/PerlinMat.cpp
  src/Material/PerlinMat.hpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimSphere.cpp
  txt
Labels: enhancement

#68 :sparkles: Material transparency
  Makefile
  src/DesignPatterns/Factory.cpp
  src/DesignPatterns/Factory.hpp
  src/Draw/draw.cpp
  src/Lights/Spot.cpp
  src/Material/TransMat.cpp
  src/Material/TransMat.hpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimSphere.cpp
Labels: enhancement

#71 ✨ Factory use template
  Makefile
  main.cpp
  src/DesignPatterns/Factory.cpp
  src/DesignPatterns/Factory.hpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimSphere.cpp
Labels: enhancement

#75 :sparkles: Handle Camera angle et pos
  .gitignore
  Makefile
  main.cpp
  src/3dDatas/Matrix4x4.hpp
  src/3dDatas/Point3D.cpp
  src/3dDatas/Point3D.hpp
  src/3dDatas/Vector3D.cpp
  src/3dDatas/Vector3D.hpp
  src/Material/ImageMat.cpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimSphere.cpp
  src/Scene/Camera.cpp
  src/Scene/Camera.hpp
  tests/test_LoadSo.cpp
  tests/test_PrimNone.cpp
  tests/test_computeTreeValues.cpp
Labels: enhancement

#76 :bug: Fix bug transparent material wrong order
  main.cpp
  src/Draw/draw.cpp
  src/Draw/hit.hpp
  src/Material/TransMat.cpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimSphere.cpp
  txt
Labels: enhancement

#81 ✨ Add init handling for all the primitives and parse sphere functionnality
  main.cpp
  src/Interfaces/Material/I_Material.hpp
  src/Interfaces/Primitive/I_Primitive.hpp
  src/Lights/Ambient.cpp
  src/Lights/Ambient.hpp
  src/Lights/Spot.cpp
  src/Lights/Spot.hpp
  src/Material/ChessboardMat.cpp
  src/Material/ChessboardMat.hpp
  src/Material/FlatMat.cpp
  src/Material/FlatMat.hpp
  src/Material/ImageMat.cpp
  src/Material/ImageMat.hpp
  src/Material/PerlinMat.cpp
  src/Material/PerlinMat.hpp
  src/Material/TransMat.cpp
  src/Material/TransMat.hpp
  src/Parsing/Parsing.cpp
  src/Parsing/Parsing.hpp
  src/Parsing/ParsingPrim.cpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimCone.hpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimCylinder.hpp
  src/Primitive/PrimNone.cpp
  src/Primitive/PrimNone.hpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimPlane.hpp
  src/Primitive/PrimSphere.cpp
  src/Primitive/PrimSphere.hpp
  tests/test_A_Light.cpp
  tests/test_A_Primitive.cpp
  tests/test_PrimNone.cpp
Labels: enhancement

#83 :sparkles: primitive limited cylinder
  Makefile
  assets/can.jpg
  src/3dDatas/Vector3D.cpp
  src/3dDatas/Vector3D.hpp
  src/DesignPatterns/Factory.hpp
  src/Primitive/PrimLimCylinder.cpp
  src/Primitive/PrimLimCylinder.hpp
Labels: enhancement

#87 ✨ Add a implementation of the OBJ file
  .gitignore
  Makefile
  include/Consts/const.hpp
  src/3dDatas/Point3D.cpp
  src/3dDatas/Point3D.hpp
  src/DesignPatterns/Factory.hpp
  src/Primitive/PrimObj.cpp
  src/Primitive/PrimObj.hpp
  tests/obj_file/computer.obj
  tests/obj_file/duck.obj
  tests/obj_file/epitech.obj
  tests/obj_file/fish.obj
  tests/obj_file/gun.obj
  tests/obj_file/lock.obj
  tests/obj_file/man.obj
  tests/obj_file/shrek.obj
Labels: enhancement

#88 :sparkles: Add skybox functionality with image loading and color retr…
  assets/skybox.jpg
  assets/space.jpg
  include/Consts/const.hpp
  include/Generation/tools.hpp
  main.cpp
  src/Draw/antiAliasing.cpp
  src/Draw/draw.cpp
  src/Draw/drawPreview.cpp
  src/Draw/skybox.cpp
  src/Draw/skybox.hpp
  src/Material/ImageMat.cpp
  src/Material/PerlinMat.cpp
Labels: enhancement

#89 :bug: fix rotation of plane
  include/Consts/const.hpp
  src/Parsing/Parsing.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimPlane.hpp
Labels: bug

#90 ✨ Add -r flag to use the program in no window mode
  include/Generation/tools.hpp
  main.cpp
  src/Draw/createImage.cpp
  src/Draw/draw.cpp
  src/Parsing/Parsing.cpp
  src/Parsing/Parsing.hpp
Labels: enhancement

#91 ✨ Add parsing of all primitives and materials
  src/Material/ChessboardMat.cpp
  src/Material/PerlinMat.cpp
  src/Material/PerlinMat.hpp
  src/Material/TransMat.cpp
  src/Material/TransMat.hpp
  src/Parsing/Parsing.cpp
  src/Parsing/Parsing.hpp
  src/Parsing/ParsingMat.cpp
  src/Parsing/ParsingPrim.cpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimNone.cpp
Labels: enhancement

#96 ✨ Add camera parsing
  include/Consts/const.hpp
  main.cpp
  src/Draw/draw.cpp
  src/Draw/drawPreview.cpp
  src/Parsing/Parsing.cpp
  src/Parsing/Parsing.hpp
  src/Parsing/ParsingCam.cpp
  src/Scene/Camera.cpp
  src/Scene/Camera.hpp
Labels: enhancement

#99 :sparkles: default value for the primitives
  src/Parsing/ParsingCam.cpp
  src/Parsing/ParsingLight.cpp
  src/Parsing/ParsingMat.cpp
  src/Parsing/ParsingPrim.cpp
Labels: enhancement

#98 :sparkles: Add Phong light
  Makefile
  src/3dDatas/Rectangle3D.hpp
  src/Draw/draw.cpp
  src/Draw/drawPreview.cpp
  src/Interfaces/Light/A_Light.cpp
  src/Interfaces/Light/A_Light.hpp
  src/Interfaces/Light/I_Light.hpp
  src/Interfaces/Material/I_Material.hpp
  src/Lights/Ambient.cpp
  src/Lights/Ambient.hpp
  src/Lights/Spot.cpp
  src/Lights/Spot.hpp
  src/Material/ChessboardMat.cpp
  src/Material/ChessboardMat.hpp
  src/Material/FlatMat.cpp
  src/Material/FlatMat.hpp
  src/Material/ImageMat.cpp
  src/Material/ImageMat.hpp
  src/Material/PerlinMat.cpp
  src/Material/PerlinMat.hpp
  src/Material/ReflectMat.cpp
  src/Material/ReflectMat.hpp
  src/Material/TransMat.cpp
  src/Material/TransMat.hpp
  src/Parsing/ParsingMat.cpp
  src/Scene/Camera.hpp
  tests/t1.txt
  tests/test_A_Light.cpp
Labels: enhancement

#105 :bug: Fix bug reflect
  main.cpp
  src/Draw/draw.cpp
  src/Draw/drawPreview.cpp
  src/Draw/skybox.cpp
  src/Parsing/ParsingCam.cpp
  src/Primitive/PrimCone.cpp
  src/Primitive/PrimCylinder.cpp
  src/Primitive/PrimLimCone.cpp
  src/Primitive/PrimLimCylinder.cpp
  src/Primitive/PrimObj.cpp
  src/Primitive/PrimPlane.cpp
  src/Primitive/PrimSphere.cpp
  src/Scene/Camera.cpp
  tests/t1.txt
Labels: bug

#107 ✨ Add default value and children parsing
  src/DesignPatterns/Factory.hpp
  src/Parsing/Parsing.cpp
  src/Parsing/Parsing.hpp
  src/Parsing/ParsingCam.cpp
  src/Parsing/ParsingLight.cpp
  src/Parsing/ParsingMat.cpp
  src/Parsing/ParsingPrim.cpp
  src/Parsing/ParsingUtils.cpp
  src/Primitive/PrimLimCylinder.cpp
  src/Primitive/PrimObj.cpp
  tests/t1.txt
Labels: enhancement

#108 ✨ Documentation
  README.md
Labels: documentation
